# -*- coding: utf-8 -*-
"""Thematic categories for az moral stories (keyed by English kebab stem)."""

from __future__ import annotations

# Ordered category list (Heading 1 order in the book)
CATEGORY_ORDER: list[str] = [
    "İman və mənəviyyat",
    "Ailə və tərbiyə",
    "Sevgi və evlilik",
    "Dostluq və insan münasibətləri",
    "Əxlaq və xarakter",
    "Söz, sükut və ünsiyyət",
    "Hikmət və həyat dərsləri",
    "Əmək, ruzi və sərvət",
    "Ədalət və cəmiyyət",
    "Yaşlanma və zaman",
    "Təmsillər və məsəllər",
    "Tarix və tanınmış şəxsiyyətlər",
]

# en_stem → category
STORY_CATEGORY: dict[str, str] = {
    # --- İman və mənəviyyat ---
    "friend-of-god": "İman və mənəviyyat",
    "gods-pleasure": "İman və mənəviyyat",
    "blessings-god-has-given": "İman və mənəviyyat",
    "let-prayer-come-and-find-you": "İman və mənəviyyat",
    "dervishs-spoons": "İman və mənəviyyat",
    "dervishs-robe": "İman və mənəviyyat",
    "dervishs-clothes": "İman və mənəviyyat",
    "o-god-heal-our-sorrows": "İman və mənəviyyat",
    "o-god-give-first-to-the-mountains-and-stones": "İman və mənəviyyat",
    "hajj-pilgrimage": "İman və mənəviyyat",
    "lawful-morsel": "İman və mənəviyyat",
    "power-of-truth": "İman və mənəviyyat",
    "forbidden-money": "İman və mənəviyyat",
    "faith-is-half-of-success": "İman və mənəviyyat",
    "idle-devil": "İman və mənəviyyat",
    "light-of-the-universe": "İman və mənəviyyat",
    "mullah-and-the-scholar": "İman və mənəviyyat",
    "price-of-a-miracle": "İman və mənəviyyat",
    "where-does-calamity-come-from": "İman və mənəviyyat",
    "calamity-and-blessing": "İman və mənəviyyat",
    "why-are-you-waiting-for-the-last-day-of-the-world": "İman və mənəviyyat",
    "to-be-fasting": "İman və mənəviyyat",
    "pray-while-washing-your-dishes": "İman və mənəviyyat",
    "if-fate-allows-we-will-meet": "İman və mənəviyyat",
    "sacrificial-meat": "İman və mənəviyyat",
    "fortieth-day-rite": "İman və mənəviyyat",
    "ramadan-prayer": "İman və mənəviyyat",
    "help-yourself-o-exalted-god": "İman və mənəviyyat",
    "stoning-the-devil": "İman və mənəviyyat",
    "drinking-the-sherbet-of-martyrdom": "İman və mənəviyyat",
    "your-hand-at-work-your-hope-in-god": "İman və mənəviyyat",
    "most-beautiful-portion": "İman və mənəviyyat",
    "eat-less-and-stay-on-the-right-path": "İman və mənəviyyat",
    "not-leaving-the-right-path": "İman və mənəviyyat",
    "church-bell": "İman və mənəviyyat",
    "my-alif-has-been-dotted": "İman və mənəviyyat",

    # --- Ailə və tərbiyə ---
    "value-of-your-family": "Ailə və tərbiyə",
    "mothers-love": "Ailə və tərbiyə",
    "mother-and-son": "Ailə və tərbiyə",
    "father-and-son": "Ailə və tərbiyə",
    "fathers-footprints": "Ailə və tərbiyə",
    "grandfather-and-grandson-at-the-market": "Ailə və tərbiyə",
    "only-my-mother-would-weep": "Ailə və tərbiyə",
    "mothers-advice-fakir-baykurt-never-forgot": "Ailə və tərbiyə",
    "from-a-wise-fathers-advice-to-his-son": "Ailə və tərbiyə",
    "raising-children": "Ailə və tərbiyə",
    "i-am-tired-mother": "Ailə və tərbiyə",
    "builder-of-the-nest": "Ailə və tərbiyə",
    "hold-my-hand": "Ailə və tərbiyə",
    "most-beautiful-gift": "Ailə və tərbiyə",
    "festive-gift": "Ailə və tərbiyə",
    "fallen-teeth": "Ailə və tərbiyə",
    "i-am-waiting-for-the-teeth": "Ailə və tərbiyə",
    "puppies-for-sale": "Ailə və tərbiyə",
    "spinach": "Ailə və tərbiyə",
    "weeds-must-be-pulled-from-the-root": "Ailə və tərbiyə",
    "rotten-seed": "Ailə və tərbiyə",

    # --- Sevgi və evlilik ---
    "early-marriage": "Sevgi və evlilik",
    "what-breaks-a-marriage": "Sevgi və evlilik",
    "advice-for-those-who-marry": "Sevgi və evlilik",
    "true-love": "Sevgi və evlilik",
    "i-kiss-your-eyes": "Sevgi və evlilik",
    "friendship-and-love": "Sevgi və evlilik",
    "do-not-let-your-hearts-part": "Sevgi və evlilik",
    "beware-of-those-you-love": "Sevgi və evlilik",
    "beloved-is-one-who-gives-love-to-people": "Sevgi və evlilik",
    "can-a-broken-heart-love-again": "Sevgi və evlilik",
    "i-love-you": "Sevgi və evlilik",
    "loving-from-afar": "Sevgi və evlilik",
    "what-is-loyalty": "Sevgi və evlilik",
    "red-dress": "Sevgi və evlilik",
    "purple-jacket": "Sevgi və evlilik",
    "mother-of-pearl-flower": "Sevgi və evlilik",
    "yellow-and-red-flowers": "Sevgi və evlilik",
    "rose": "Sevgi və evlilik",
    "what-women-have-endured-in-this-world": "Sevgi və evlilik",
    "woman-and-the-mirror": "Sevgi və evlilik",

    # --- Dostluq və insan münasibətləri ---
    "friendship-of-horses": "Dostluq və insan münasibətləri",
    "i-want-a-friend": "Dostluq və insan münasibətləri",
    "those-you-should-not-befriend": "Dostluq və insan münasibətləri",
    "know-your-friend": "Dostluq və insan münasibətləri",
    "your-friends": "Dostluq və insan münasibətləri",
    "how-we-treat-people": "Dostluq və insan münasibətləri",
    "humanity": "Dostluq və insan münasibətləri",
    "compliment": "Dostluq və insan münasibətləri",
    "meddling-in-others-lives": "Dostluq və insan münasibətləri",
    "gossip": "Dostluq və insan münasibətləri",
    "people-who-need-something-from-you": "Dostluq və insan münasibətləri",
    "spend-your-time-with-people": "Dostluq və insan münasibətləri",
    "to-meet-and-to-know": "Dostluq və insan münasibətləri",
    "if-the-road-does-not-tire-you-it-is-because-of-your-companion": "Dostluq və insan münasibətləri",
    "go-but-come-again": "Dostluq və insan münasibətləri",
    "welcome-my-bey": "Dostluq və insan münasibətləri",
    "glass-of-milk": "Dostluq və insan münasibətləri",
    "handful-of-roasted-chickpeas": "Dostluq və insan münasibətləri",
    "pair-of-boots": "Dostluq və insan münasibətləri",
    "sound-of-the-doorbell": "Dostluq və insan münasibətləri",
    "to-be-alone": "Dostluq və insan münasibətləri",
    "mockery-is-unacceptable": "Dostluq və insan münasibətləri",
    "how-to-ward-off-insults": "Dostluq və insan münasibətləri",
    "compassion": "Dostluq və insan münasibətləri",
    "to-forgive": "Dostluq və insan münasibətləri",
    "permission-or-apology": "Dostluq və insan münasibətləri",
    "why-people-shout-when-they-argue": "Dostluq və insan münasibətləri",
    "discussion-and-conflict": "Dostluq və insan münasibətləri",
    "everyone-is-the-same-here": "Dostluq və insan münasibətləri",

    # --- Əxlaq və xarakter ---
    "being-human": "Əxlaq və xarakter",
    "dont-open-your-mouth": "Əxlaq və xarakter",
    "dont-be-words-for-mouths-dust-for-feet": "Əxlaq və xarakter",
    "do-not-do-these-things": "Əxlaq və xarakter",
    "flower-of-honesty": "Əxlaq və xarakter",
    "telling-lies": "Əxlaq və xarakter",
    "generous-man": "Əxlaq və xarakter",
    "he-would-not-have-given-so-little": "Əxlaq və xarakter",
    "who-handles-honey-licks-his-finger": "Əxlaq və xarakter",
    "honey-or-dry-bread": "Əxlaq və xarakter",
    "goose-to-be-plucked": "Əxlaq və xarakter",
    "you-cannot-descend-a-well-on-his-rope": "Əxlaq və xarakter",
    "that-was-not-your-right": "Əxlaq və xarakter",
    "to-be-self-confident": "Əxlaq və xarakter",
    "other-peoples-opinions": "Əxlaq və xarakter",
    "our-qualities-can-become-our-enemies": "Əxlaq və xarakter",
    "to-be-cool-headed": "Əxlaq və xarakter",
    "think-speak-and-act-positively": "Əxlaq və xarakter",
    "try-to-think-this-way": "Əxlaq və xarakter",
    "may-your-face-always-smile": "Əxlaq və xarakter",
    "dont-say-i-couldnt-deliver-or-i-couldnt-manage": "Əxlaq və xarakter",
    "to-give-up": "Əxlaq və xarakter",
    "attitude-toward-a-problem": "Əxlaq və xarakter",
    "turning-hardship-into-opportunity": "Əxlaq və xarakter",
    "everything-is-in-our-own-hands": "Əxlaq və xarakter",
    "be-sure-of-your-purpose": "Əxlaq və xarakter",
    "mature-person": "Əxlaq və xarakter",
    "education-or-character": "Əxlaq və xarakter",
    "i-got-busy-with-cleaning": "Əxlaq və xarakter",
    "expressions-you-should-stay-away-from": "Əxlaq və xarakter",
    "avoid-these-questions": "Əxlaq və xarakter",
    "meaningless-question": "Əxlaq və xarakter",
    "no-one-listens-to-constant-complainers": "Əxlaq və xarakter",
    "do-not-complain-about-any-day-you-have-lived": "Əxlaq və xarakter",
    "i-am-aware-now": "Əxlaq və xarakter",
    "how-can-i-escape-my-thoughts": "Əxlaq və xarakter",
    "not-every-sorrow-is-told-to-people": "Əxlaq və xarakter",
    "explaining-ones-sorrow": "Əxlaq və xarakter",
    "strength-and-sorrow": "Əxlaq və xarakter",
    "strongest-shield": "Əxlaq və xarakter",
    "three-best-things": "Əxlaq və xarakter",
    "i-would-not-trade-it-for-anything": "Əxlaq və xarakter",

    # --- Söz, sükut və ünsiyyət ---
    "tongue": "Söz, sükut və ünsiyyət",
    "what-is-a-word": "Söz, sükut və ünsiyyət",
    "word-and-silence": "Söz, sükut və ünsiyyət",
    "saying-the-word-in-its-place": "Söz, sükut və ünsiyyət",
    "silence": "Söz, sükut və ünsiyyət",
    "communication": "Söz, sükut və ünsiyyət",
    "say-what-you-know": "Söz, sükut və ünsiyyət",
    "one-who-knows-and-the-one-who-does-not": "Söz, sükut və ünsiyyət",
    "shepherds-word": "Söz, sükut və ünsiyyət",
    "shepherd-must-be-called": "Söz, sükut və ünsiyyət",
    "candles-conversation": "Söz, sükut və ünsiyyət",
    "silent-corridor": "Söz, sükut və ünsiyyət",

    # --- Hikmət və həyat dərsləri ---
    "searching": "Hikmət və həyat dərsləri",
    "spare-time": "Hikmət və həyat dərsləri",
    "it-is-in-vain": "Hikmət və həyat dərsləri",
    "if-i-dont-do-it-these-days-the-world-wont-collapse": "Hikmət və həyat dərsləri",
    "this-boat-is-empty-too": "Hikmət və həyat dərsləri",
    "where-does-this-road-go": "Hikmət və həyat dərsləri",
    "more-effective-way": "Hikmət və həyat dərsləri",
    "different-path": "Hikmət və həyat dərsləri",
    "sowing-millet-at-the-bottom": "Hikmət və həyat dərsləri",
    "diderot-effect": "Hikmət və həyat dərsləri",
    "most-beautiful-places-in-the-world": "Hikmət və həyat dərsləri",
    "what-it-means-to-be-late": "Hikmət və həyat dərsləri",
    "blind-who-have-eyes": "Hikmət və həyat dərsləri",
    "no-need-to-be-sane-when-everyone-is-mad": "Hikmət və həyat dərsləri",
    "life-lesson": "Hikmət və həyat dərsləri",
    "what-matters-in-life": "Hikmət və həyat dərsləri",
    "what-we-learn-in-life": "Hikmət və həyat dərsləri",
    "hayats-life-story": "Hikmət və həyat dərsləri",
    "two-bowls-of-water": "Hikmət və həyat dərsləri",
    "human-emerged": "Hikmət və həyat dərsləri",
    "it-wont-go-to-waste": "Hikmət və həyat dərsləri",
    "nothing-is-ever-truly-lost": "Hikmət və həyat dərsləri",
    "living-in-the-past": "Hikmət və həyat dərsləri",
    "blind-well": "Hikmət və həyat dərsləri",
    "windmill-turning-in-still-air": "Hikmət və həyat dərsləri",
    "magnificent-lesson": "Tarix və tanınmış şəxsiyyətlər",
    "newtons-second-law": "Hikmət və həyat dərsləri",
    "what-do-i-need-it-for": "Hikmət və həyat dərsləri",
    "road-to-the-cotton-field": "Hikmət və həyat dərsləri",
    "pawn-and-the-king": "Hikmət və həyat dərsləri",
    "properties-of-water": "Hikmət və həyat dərsləri",
    "to-be-full-or-to-be-gone": "Hikmət və həyat dərsləri",
    "to-dream": "Hikmət və həyat dərsləri",
    "secret-of-living-well-and-longevity": "Hikmət və həyat dərsləri",
    "life-is-short": "Hikmət və həyat dərsləri",
    "dead-remain-in-life": "Hikmət və həyat dərsləri",
    "if-the-door-before-you-wont-open-it-is-not-your-door": "Hikmət və həyat dərsləri",
    "three-statues": "Hikmət və həyat dərsləri",
    "three-landscapes": "Hikmət və həyat dərsləri",
    "three-questions": "Hikmət və həyat dərsləri",
    "three-essential-things-for-a-city": "Tarix və tanınmış şəxsiyyətlər",
    "liver": "Hikmət və həyat dərsləri",
    "doctors-appointment": "Hikmət və həyat dərsləri",
    "from-the-memoirs-of-a-lady-from-istanbul": "Hikmət və həyat dərsləri",
    "bookstore": "Hikmət və həyat dərsləri",
    "teacher-hello-do-you-remember-me": "Hikmət və həyat dərsləri",
    "lecturer-and-the-groom": "Hikmət və həyat dərsləri",

    # --- Əmək, ruzi və sərvət ---
    "fish-shop": "Əmək, ruzi və sərvət",
    "grocery-shop-and-the-supermarket": "Əmək, ruzi və sərvət",
    "chief-accountant-and-the-ceo": "Əmək, ruzi və sərvət",
    "garden-and-the-gardener": "Əmək, ruzi və sərvət",
    "we-are-rich": "Əmək, ruzi və sərvət",
    "everyone-has-work-to-do": "Əmək, ruzi və sərvət",
    "organization-without-an-action-plan": "Əmək, ruzi və sərvət",
    "henry-fords-choice": "Əmək, ruzi və sərvət",
    "hot-bread": "Əmək, ruzi və sərvət",
    "mercedes": "Əmək, ruzi və sərvət",
    "why-am-i-poor": "Əmək, ruzi və sərvət",
    "credit-ledger": "Əmək, ruzi və sərvət",
    "baklava": "Əmək, ruzi və sərvət",
    "scarf-seller": "Əmək, ruzi və sərvət",
    "weight-of-the-oil": "Əmək, ruzi və sərvət",
    "do-you-have-spending-money": "Əmək, ruzi və sərvət",
    "his-hand-is-at-work": "Əmək, ruzi və sərvət",
    "pay-rent-for-the-water": "Əmək, ruzi və sərvət",
    "former-minister-at-the-seminar": "Əmək, ruzi və sərvət",

    # --- Ədalət və cəmiyyət ---
    "with-this-nation-the-world-can-be-conquered": "Ədalət və cəmiyyət",
    "just-verdict-of-the-frankfurt-judge": "Ədalət və cəmiyyət",
    "woman-whose-house-was-robbed": "Ədalət və cəmiyyət",
    "bedouin-whose-camel-was-stolen": "Ədalət və cəmiyyət",
    "homeland-and-land": "Ədalət və cəmiyyət",
    "why-injustice-when-there-is-justice": "Ədalət və cəmiyyət",
    "sharing-justice": "Ədalət və cəmiyyət",
    "skins-of-the-lambs": "Ədalət və cəmiyyət",
    "nazim-hikmet-in-bursa-prison": "Ədalət və cəmiyyət",
    "bell-to-hang-on-the-cats-neck": "Ədalət və cəmiyyət",

    # --- Yaşlanma və zaman ---
    "what-changed-after-sixty": "Yaşlanma və zaman",
    "for-those-who-have-reached-sixty": "Yaşlanma və zaman",
    "aging": "Yaşlanma və zaman",

    # --- Təmsillər və məsəllər ---
    "lions-footprint": "Təmsillər və məsəllər",
    "elephant-and-the-rope": "Təmsillər və məsəllər",
    "donkeys-law": "Təmsillər və məsəllər",
    "two-donkeys": "Təmsillər və məsəllər",
    "fly-in-the-china-shop": "Təmsillər və məsəllər",
    "ant-that-carries-water": "Təmsillər və məsəllər",
    "turtles-wrong-calculation": "Təmsillər və məsəllər",
    "hunters-description": "Təmsillər və məsəllər",

    # --- Tarix və tanınmış şəxsiyyətlər ---
    "albrecht-durer": "Tarix və tanınmış şəxsiyyətlər",
    "architect-sinan-dies-in-a-house-without-water": "Tarix və tanınmış şəxsiyyətlər",
    "mihrimah-sultan-and-architect-sinan": "Tarix və tanınmış şəxsiyyətlər",
}


def validate_against(stems: set[str]) -> tuple[list[str], list[str]]:
    """Return (missing_from_map, unknown_in_map)."""
    mapped = set(STORY_CATEGORY)
    return sorted(stems - mapped), sorted(mapped - stems)
