# -*- coding: utf-8 -*-
"""Download self-hosted WOFF2 files for the site typefaces."""
from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FONTS_DIR = ROOT / "assets" / "fonts"
CSS_PATH = ROOT / "assets" / "fonts.css"

# Variable ranges cover the weights used in site.css.
CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Fraunces:opsz,wght@9..144,500..700"
    "&family=Source+Serif+4:opsz,wght@8..60,400..600"
    "&family=Source+Sans+3:wght@400..700"
    "&display=swap"
)
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)
_URL_RE = re.compile(r"url\((https://fonts\.gstatic\.com/[^)]+)\)")
_FACE_RE = re.compile(r"@font-face\s*\{[^{}]+\}", re.S)

FAMILY_SLUG = {
    "Fraunces": "fraunces",
    "Source Serif 4": "source-serif-4",
    "Source Sans 3": "source-sans-3",
}


def _fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read()


def _family_slug(face: str) -> str:
    m = re.search(r"font-family:\s*'([^']+)'", face)
    name = m.group(1) if m else "font"
    return FAMILY_SLUG.get(name, re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-"))


def _subset_slug(face: str, index: int) -> str:
    comment = re.search(r"/\*\s*([^*]+?)\s*\*/", face)
    if comment:
        return re.sub(r"[^a-z0-9]+", "-", comment.group(1).lower()).strip("-")
    return f"subset-{index}"


def main() -> None:
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    css = _fetch(CSS_URL).decode("utf-8")
    faces = _FACE_RE.findall(css)
    if not faces:
        raise SystemExit("Google Fonts CSS had no @font-face blocks")
    out_faces: list[str] = []
    seen_names: set[str] = set()
    for i, face in enumerate(faces, start=1):
        url_m = _URL_RE.search(face)
        if not url_m:
            continue
        url = url_m.group(1)
        family = _family_slug(face)
        subset = _subset_slug(face, i)
        filename = f"{family}-{subset}.woff2"
        if filename in seen_names:
            filename = f"{family}-{subset}-{i}.woff2"
        seen_names.add(filename)
        dest = FONTS_DIR / filename
        if not dest.is_file():
            dest.write_bytes(_fetch(url))
        local = face.replace(url, f"fonts/{filename}")
        local = local.replace("format('woff2')", 'format("woff2")')
        out_faces.append(local.strip())
    header = (
        "/* Self-hosted Fraunces, Source Serif 4, Source Sans 3 (OFL).\n"
        "   Generated by tools/vendor_google_fonts.py — do not load fonts.googleapis.com. */\n"
    )
    CSS_PATH.write_text(header + "\n".join(out_faces) + "\n", encoding="utf-8")
    license_path = FONTS_DIR / "OFL.txt"
    if not license_path.is_file():
        license_path.write_text(
            "These font files are licensed under the SIL Open Font License 1.1.\n"
            "Fraunces, Source Serif 4, and Source Sans 3.\n"
            "https://scripts.sil.org/OFL\n",
            encoding="utf-8",
        )
    print(f"fonts: {len(out_faces)} faces -> {CSS_PATH}")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"vendor_google_fonts failed: {exc}", file=sys.stderr)
        raise
